name: blackjack deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./blackjack

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blackjack/build
          destination_dir: blackjack
